### ISSUE TITLE
kendo-translate command on Windows

### ISSUE THREAD

**Issue by nlgi** [telerik/kendo-angular-messages#11]
Hi,

I got this error on cmd window : 'kendo-translate' is not recognized as internal command.
I tried to : 
 - Execute the script directly in node_modules/@progress/kendo-angular-messages/bin
 - Run it into cmd "as admin"
 - Run it into node cmd

Can I have some help?

Many thanks,

**Comment by tsvetomir** [comment]
Please try again with version 1.5.1

**Comment by nlgi** [comment]
Haha sorry about the old title of this issue!

It's running on 1.6, but there is a script error: 
`kendo-translate src\i18n\messages.fr.xlf --locale fr-FR`
I tried with "/" too.
`kendo-translate src/i18n/messages.fr.xlf --locale fr-FR`

Command line returns: 
`{ AssertionError: obj needs to be an object
    at JSONPath.query (C:\Users\nlgi\AppData\Roaming\npm\node_modules\@progress\kendo-angular-messages\node_modules\jsonpath\lib\index.js:91:10) 

    at translate (C:\Users\nlgi\AppData\Roaming\npm\node_modules\@progress\kendo-angular-messages\node_modules\xlf-translate\translate.js:13:22)

    at Task.e [as fork] (C:\Users\nlgi\AppData\Roaming\npm\node_modules\@progress\kendo-angular-messages\bin\kendo-translate.js:89:23)

    at C:\Users\nlgi\AppData\Roaming\npm\node_modules\@progress\kendo-angular-messages\node_modules\data.task\lib\task.js:117:19

    at C:\Users\nlgi\AppData\Roaming\npm\node_modules\@progress\kendo-angular-messages\node_modules\data.task\lib\task.js:167:18

    at C:\Users\nlgi\AppData\Roaming\npm\node_modules\@progress\kendo-angular-messages\node_modules\data.task\lib\task.js:96:14

    at C:\Users\nlgi\AppData\Roaming\npm\node_modules\@progress\kendo-angular-messages\bin\kendo-translate.js:46:29

    at Parser.<anonymous> (C:\Users\nlgi\AppData\Roaming\npm\node_modules\@progress\kendo-angular-messages\node_modules\xml2js\lib\xml2js.js:489:18)

    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)  name: 'AssertionError',  actual: false, expected: true, operator: '==', message: 'obj needs to be an object',  generatedMessage: false }`

Many thanks,

**Comment by ipeshev** [comment]
Could you provide your xlf file. It is working for me with sample xlf files

**Comment by tsvetomir** [comment]
The XLF files are generated by the `ng-xi18n` tool by [extracting the messages](http://www.telerik.com/kendo-angular-ui/components/localization/messages/#toc-extract-the-messages) from the application.

**Comment by nlgi** [comment]
Works just perfectly.

Many thanks,
